package com.androidnexus.controller;

import com.androidnexus.adb.CommandExecutor;
import com.androidnexus.exception.AdbException;
import com.androidnexus.utils.Constants;
import com.androidnexus.utils.FileNameGenerator;

/**
 * Captures screenshots from the connected Android device.
 *
 * Three-step process:
 *   1. screencap -p on the device → saves PNG to device storage
 *   2. adb pull → transfers the PNG to the local machine
 *   3. adb shell rm → cleans up the temp file on the device
 *
 * The screenshot is saved to the local screenshots folder defined in
 * {@link Constants#LOCAL_SCREENSHOT_FOLDER} with a timestamped filename
 * generated by {@link FileNameGenerator}.
 *
 * Why not pipe screencap directly to local file?
 *   "adb exec-out screencap -p > file.png" works on some platforms but
 *   is unreliable on Windows due to line-ending corruption (0x0A → 0x0D 0x0A).
 *   The capture-pull-delete approach is universally reliable.
 */
public class ScreenshotController {

    /**
     * Captures a screenshot and saves it locally with a timestamped filename.
     *
     * @throws AdbException if any step of the capture-pull-delete sequence fails
     */
    public static void takeScreenshot() throws AdbException {

        String fileName = FileNameGenerator.generateScreenshotName();

        String phonePath = Constants.PHONE_STORAGE_DIRECTORY + fileName;

        // Step 1: Capture screenshot on device
        CommandExecutor.executeCommand(
                "adb", "shell", "screencap", "-p", phonePath
        );

        // Step 2: Pull to local machine
        CommandExecutor.executeCommand(
                "adb", "pull", phonePath,
                Constants.LOCAL_SCREENSHOT_FOLDER + "\\" + fileName
        );

        // Step 3: Clean up temp file on device
        CommandExecutor.executeCommand(
                "adb", "shell", "rm", phonePath
        );
    }
}
